development:
  clients:
    default:
      database: helena_demo_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: helena_demo_test
      hosts:
        - localhost:27017
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
      options:  
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
